**Real-Time Intrusion Detection System**

Problem Statement : Real-time Intrusion Detection System (IDS): Create a machine learning-based
IDS that can identify and respond to threats in real time.

Importing libraries

Data **Preprocessing**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,StratifiedKFold,GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import make_scorer, roc_auc_score
import scipy
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [ ]:
#variable definition
columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land', 'wrong_fragment',
           'urgent', 'hot', 'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell', 'su_attempted',
           'num_root', 'num_file_creations', 'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
           'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate',
           'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
           'dst_host_same_srv_rate', 'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
           'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate',
           'attack', 'level']

In [ ]:
# Load the datasets
train_df = pd.read_csv("KDDTrain+.txt", header=None, names=columns, low_memory=False)
test_df = pd.read_csv("KDDTest+.txt", header=None, names=columns, low_memory=False)
train_df.head(100)

FileNotFoundError: [Errno 2] No such file or directory: 'KDDTrain+.txt'

In [ ]:
train_df.shape

In [ ]:
test_df.shape

In [ ]:
train_df.info()

In [ ]:
test_df.info()

In [ ]:
test_df.nunique()

In [ ]:
test_df.isnull().sum()

In [ ]:
train_df.nunique()

In [ ]:
train_df.isnull().sum()

In [ ]:
# Convert appropriate columns to numeric types, handling errors
for column in train_df.columns:
    if column not in ['protocol_type', 'service', 'flag', 'attack', 'binary_attack']:
        train_df[column] = pd.to_numeric(train_df[column], errors='coerce')
        test_df[column] = pd.to_numeric(test_df[column], errors='coerce')

# Handle non-numeric values
train_df.fillna(0, inplace=True)
test_df.fillna(0, inplace=True)

**Model Training:**

Checking for outliers

In [ ]:
import matplotlib.pyplot as plt

# Plot box plots for all numerical features in the train dataset
train_df.plot(kind='box', subplots=True, layout=(15, 3), figsize=(20, 40))
plt.tight_layout()  # Adjust subplots to fit into figure area.
plt.show()

In [ ]:
train_df['attack'].value_counts()

In [ ]:

train_df['binary_attack'] = train_df.attack.map(lambda a: "normal" if a == 'normal' else "abnormal")
train_df.drop('attack', axis=1, inplace=True)

test_df['binary_attack'] = test_df.attack.map(lambda a: "normal" if a == 'normal' else "abnormal")
test_df.drop('attack', axis=1, inplace=True)

In [ ]:

plt.figure(figsize=(12, 6))
sns.countplot(data=train_df, x='binary_attack', palette='Set2')
plt.title('Distribution of Attack Types')
plt.xlabel('Attack Type')
plt.ylabel('Count')
plt.show()

In [ ]:

plt.figure(figsize=(12, 6))
sns.countplot(data=train_df, x='protocol_type', palette='muted')
plt.title('Distribution of Protocol Types')
plt.xlabel('Protocol Type')
plt.ylabel('Count')
plt.show()

Encoding

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

combined_df = pd.concat([train_df, test_df], axis=0)

le = LabelEncoder()
for column in ['protocol_type', 'service', 'flag', 'binary_attack']:
    combined_df[column] = le.fit_transform(combined_df[column])

Splitting training data and testing data

In [ ]:

train_df = combined_df.iloc[:len(train_df), :]
test_df = combined_df.iloc[len(train_df):, :]

x_train = train_df.drop('binary_attack', axis=1)
y_train = train_df['binary_attack']
x_test = test_df.drop('binary_attack', axis=1)
y_test = test_df['binary_attack']

Graphs

In [ ]:
from sklearn.feature_selection import mutual_info_classif
mutual_info = mutual_info_classif(x_train, y_train)
mutual_info = pd.Series(mutual_info)
mutual_info.index = x_train.columns
mutual_info.sort_values(ascending=False)

In [ ]:
mutual_info.sort_values(ascending=False).plot.bar(figsize=(20, 8));

In [ ]:
col=['service', 'flag', 'src_bytes', 'dst_bytes', 'logged_in',
       'same_srv_rate', 'diff_srv_rate', 'dst_host_srv_count',
       'dst_host_same_srv_rate', 'dst_host_diff_srv_rate']
x_train=x_train[col]
x_test=x_test[col]

In [ ]:
plt.figure(figsize=(12,10))
p=sns.heatmap(x_train.corr(), annot=True,cmap ='RdYlGn')

Scaling

In [ ]:
# Scaling the data
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

**Testing and Evaluation:** Binary classification model

In [ ]:
# we'll initialize each model and store it by name in a dictionary
models = {}

# Logistic Regression
from sklearn.linear_model import LogisticRegression
models['Logistic Regression'] = LogisticRegression()

# Support Vector Machines
from sklearn.svm import LinearSVC
models['Support Vector Machines linear'] = LinearSVC()
models['Support Vector Machines plonomial'] = SVC(kernel='poly')
models['Support Vector Machines RBf'] =  SVC(C=100.0)

# Decision Trees
from sklearn.tree import DecisionTreeClassifier
models['Decision Trees'] = DecisionTreeClassifier(max_depth=3)

# Random Forest
from sklearn.ensemble import RandomForestClassifier
models['Random Forest'] = RandomForestClassifier()

# Naive Bayes
from sklearn.naive_bayes import GaussianNB
models['Naive Bayes'] = GaussianNB()

# K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
models['K-Nearest Neighbor'] = KNeighborsClassifier(n_neighbors=20)

In [ ]:
# Initialize each model and store it by name in a dictionary
models = {
    'Logistic Regression': LogisticRegression(),
    'Support Vector Machines linear': LinearSVC(),
    'Support Vector Machines polynomial': SVC(kernel='poly'),
    'Support Vector Machines RBF': SVC(C=100.0),
    'Decision Trees': DecisionTreeClassifier(max_depth=3),
    'Random Forest': RandomForestClassifier(),
    'Naive Bayes': GaussianNB(),
    'K-Nearest Neighbor': KNeighborsClassifier(n_neighbors=20)
}

# Train and evaluate each model
accuracy, precision, recall = {}, {}, {}

for key in models.keys():
    # Fit the classifier
    models[key].fit(x_train, y_train)

    # Make predictions
    predictions = models[key].predict(x_test)

    # Calculate metrics
    accuracy[key] = accuracy_score(predictions, y_test)
    precision[key] = precision_score(predictions, y_test, average='weighted')
    recall[key] = recall_score(predictions, y_test, average='weighted')

# Display results
import pandas as pd

results_df = pd.DataFrame({
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall
})

print(results_df)

# Create a DataFrame for the metrics
df_metrics = pd.DataFrame({
    'Accuracy': accuracy,
    'Precision': precision,
    'Recall': recall
})

# Plot the bar chart for model metrics
ax = df_metrics.plot.barh()
ax.legend(ncol=len(models.keys()), bbox_to_anchor=(0, 1), loc='lower left', prop={'size': 14})
plt.tight_layout()
plt.show()

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_curve, auc
from sklearn.datasets import make_classification

In [ ]:
# Train and evaluate each model (replace with your actual training and evaluation steps)
for name, model in models.items():
    model.fit(x_train, y_train)

# Plot ROC curve
plt.figure(figsize=(10, 8))
for name, model in models.items():
    if hasattr(model, "predict_proba"):  # Check if the model has predict_proba method
        prob_pos = model.predict_proba(x_test)[:, 1]
    else:  # Use decision function for SVC models
        prob_pos = model.decision_function(x_test)
        prob_pos = \
            (prob_pos - prob_pos.min()) / (prob_pos.max() - prob_pos.min())
    fpr, tpr, _ = roc_curve(y_test, prob_pos)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, lw=2, label=f'{name} (area = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curves')
plt.legend(loc='lower right')
plt.show()

In [ ]:
import joblib

best_model = models['Support Vector Machines RBF']
joblib.dump(best_model, 'svm_rbf_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

In [ ]:
# Compare predictions with actual values
comparison_df = pd.DataFrame({
    'Actual': y_test,
    'Predicted': predictions
})

# Show the first few rows
print(comparison_df.head(20))

In [ ]:
from sklearn.metrics import accuracy_score
import joblib
best_model=joblib.load('svm_rbf_model.pkl')
predictions = best_model.predict(x_test)
print(f"Accuracy: {accuracy_score(y_test, predictions)}")

In [ ]:
import joblib


loaded_model = joblib.load('svm_rbf_model.pkl')
loaded_scaler = joblib.load('scaler.pkl')

# Verify model predictions on new data
test_data = pd.DataFrame({
    'service': [1],
    'flag': [2],
    'src_bytes': [200],
    'dst_bytes': [300],
    'logged_in': [1],
    'same_srv_rate': [0.5],
    'diff_srv_rate': [0.5],
    'dst_host_srv_count': [10],
    'dst_host_same_srv_rate': [0.7],
    'dst_host_diff_srv_rate': [0.2]
})


scaled_test_data = loaded_scaler.transform(test_data)


prediction = loaded_model.predict(scaled_test_data)
print(f"Prediction: {prediction}")

# WORKING CODE

In [ ]:
import pandas as pd
import joblib
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Load the full dataset with labels
df_full = pd.read_csv("logfile.csv")  # or ',' depending on your file

# Drop both label columns for training scaler
X = df_full.drop(columns=["level", "binary_attack"], errors="ignore")

# Categorical and numerical columns
categorical_cols = ["protocol_type", "service", "flag"]
numeric_cols = X.columns.difference(categorical_cols).tolist()

# Build preprocessing pipeline
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numeric_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
])

scaling_pipeline = Pipeline([
    ("preprocessor", preprocessor)
])

# Fit on full training data
scaling_pipeline.fit(X)

# Save the pipeline
joblib.dump(scaling_pipeline, "scaler_pipeline.pkl")
print("✅ Scaler pipeline trained and saved as 'scaler_pipeline.pkl'")

✅ Scaler pipeline trained and saved as 'scaler_pipeline.pkl'

In [ ]:
# Load the saved pipeline
pipeline = joblib.load("scaler_pipeline.pkl")

# Load user-uploaded logfile (WITHOUT the labels)
log_df = pd.read_csv("logfile.csv")  # or ','

# Drop only the 'level' column (if it's there)
log_X = log_df.drop(columns=["level"], errors="ignore")

# Transform the features
scaled_features = pipeline.transform(log_X)

print("✅ Scaled data ready for prediction!")

✅ Scaled data ready for prediction!

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.svm import SVC
from sklearn.metrics import classification_report
import joblib

df = pd.read_csv("final_train.csv")

X = df.drop(columns=["level", "binary_attack"])
y = df["binary_attack"]

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

categorical_cols = ["protocol_type", "service", "flag"]
numerical_cols = X.columns.difference(categorical_cols).tolist()

preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
])

svm_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", SVC(kernel="rbf", C=100.0))
])
svm_pipeline.fit(x_train, y_train)
y_pred = svm_pipeline.predict(x_test)
print(classification_report(y_test, y_pred))
joblib.dump(svm_pipeline, "svm_rbf_kdd_model.pkl")
print("✅ SVM RBF model saved as 'svm_rbf_kdd_model.pkl'")

              precision    recall  f1-score   support

    abnormal       1.00      1.00      1.00     11773
      normal       1.00      1.00      1.00     13422

    accuracy                           1.00     25195
   macro avg       1.00      1.00      1.00     25195
weighted avg       1.00      1.00      1.00     25195

✅ SVM RBF model saved as 'svm_rbf_kdd_model.pkl'

In [ ]:
from sklearn.metrics import accuracy_score
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")

Accuracy: 0.9960706489382815

In [ ]:
log_df = pd.read_csv("logfile11.csv")

X_log = log_df.drop(columns=["level", "binary_attack"], errors="ignore")

svm_pipeline = joblib.load("svm_rbf_kdd_model.pkl")

log_predictions = svm_pipeline.predict(X_log)

output_df = log_df.copy()
output_df["predicted_attack"] = log_predictions
output_df.to_csv("log_with_predictions.csv", index=False)

print("✅ Predictions added to 'log_with_predictions.csv'")

✅ Predictions added to 'log_with_predictions.csv'

In [ ]:
accuracy = accuracy_score(y_true, log_predictions)
print(f"✅ Accuracy: {accuracy:.4f}")

✅ Accuracy: 0.7893

In [ ]:
df_1 = pd.read_csv("log_with_predictions.csv")
df_1

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,Unnamed: 41,predicted_attack
0,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1,1,0,0,19,abnormal
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0,0,1,1,21,abnormal
2,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0,0,1,1,21,abnormal
3,0,tcp,http,SF,327,467,0,0,0,0,...,1.00,0.00,0.01,0.03,0,0,0,0,21,normal
4,0,tcp,http,SF,245,351,0,0,0,0,...,1.00,0.00,0.00,0.01,0,0,0,0,21,normal

In [ ]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn
import torch.optim as optim

# Load dataset
df = pd.read_csv("final_train.csv")

# Encode label column
df['binary_attack'] = df['binary_attack'].map({'normal': 0, 'abnormal': 1})

# Encode categorical columns
cat_cols = ['protocol_type', 'service', 'flag']
encoders = {col: LabelEncoder().fit(df[col]) for col in cat_cols}
for col in cat_cols:
    df[col] = encoders[col].transform(df[col])

# Separate features and labels
X = df.drop(['binary_attack'], axis=1)
y = df['binary_attack']

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)

# DataLoader
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [ ]:
class IntrusionNet(nn.Module):
    def __init__(self, input_dim):
        super(IntrusionNet, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

In [ ]:
model = IntrusionNet(input_dim=X_train.shape[1])
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 20
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs}, Loss: {running_loss/len(train_loader):.4f}")

Epoch 1/20, Loss: 0.0463
Epoch 2/20, Loss: 0.0201
Epoch 3/20, Loss: 0.0198
Epoch 4/20, Loss: 0.0178
Epoch 5/20, Loss: 0.0152
Epoch 6/20, Loss: 0.0159
Epoch 7/20, Loss: 0.0139
Epoch 8/20, Loss: 0.0125
Epoch 9/20, Loss: 0.0135
Epoch 10/20, Loss: 0.0132
Epoch 11/20, Loss: 0.0130
Epoch 12/20, Loss: 0.0110
Epoch 13/20, Loss: 0.0115
Epoch 14/20, Loss: 0.0128
Epoch 15/20, Loss: 0.0115
Epoch 16/20, Loss: 0.0119
Epoch 17/20, Loss: 0.0109
Epoch 18/20, Loss: 0.0117
Epoch 19/20, Loss: 0.0115
Epoch 20/20, Loss: 0.0101

In [ ]:
# Load final_test.csv
df_test = pd.read_csv("final_test.csv")

# Encode label column if it exists
if 'binary_attack' in df_test.columns:
    df_test['binary_attack'] = df_test['binary_attack'].map({'normal': 0, 'abnormal': 1})
    has_labels = True
else:
    has_labels = False

# Encode categorical columns using the same encoders
for col in cat_cols:
    df_test[col] = encoders[col].transform(df_test[col])

# Separate features and labels
if has_labels:
    X_final_test = df_test.drop(['binary_attack'], axis=1)
    y_final_test = df_test['binary_attack']
else:
    X_final_test = df_test

# Normalize features using the same scaler
X_final_test_scaled = scaler.transform(X_final_test)

# Convert to tensor
X_final_tensor = torch.tensor(X_final_test_scaled, dtype=torch.float32)

# Make predictions
model.eval()
with torch.no_grad():
    predictions = model(X_final_tensor).squeeze()
    predicted_labels = (predictions >= 0.5).int()

if has_labels:
    y_final_tensor = torch.tensor(y_final_test.values, dtype=torch.int32)
    accuracy = (predicted_labels == y_final_tensor).float().mean()
    print(f"Accuracy on final_test.csv: {accuracy:.4f}")
else:
    # Print or save predictions if labels are not available
    print("Predictions on final_test.csv:")
    print(predicted_labels.numpy())

Accuracy on final_test.csv: 0.8561

In [ ]:
torch.save(model, 'deep_learning.pkl')

In [ ]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from torch.utils.data import TensorDataset, DataLoader
import torch.nn as nn
import torch.optim as optim
import numpy as np

# Load dataset
df = pd.read_csv("final_train.csv")

# Prepare features and labels
X = df.drop(columns=["level", "binary_attack"])
y = df["binary_attack"].map({'normal': 0, 'abnormal': 1})

# Define columns
categorical_cols = ["protocol_type", "service", "flag"]
numerical_cols = X.columns.difference(categorical_cols).tolist()

# ColumnTransformer for preprocessing
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), numerical_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
])

# Fit and transform training data
X_processed = preprocessor.fit_transform(X)

# Split into train and test
X_train_np, X_test_np, y_train_np, y_test_np = train_test_split(
    X_processed, y.values, test_size=0.2, random_state=42
)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train_np.toarray() if hasattr(X_train_np, "toarray") else X_train_np, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_np.toarray() if hasattr(X_test_np, "toarray") else X_test_np, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_np, dtype=torch.float32).unsqueeze(1)
y_test_tensor = torch.tensor(y_test_np, dtype=torch.float32).unsqueeze(1)

# DataLoaders
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

# Define the model
class IntrusionNet(nn.Module):
    def __init__(self, input_dim):
        super(IntrusionNet, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

model = IntrusionNet(input_dim=X_train_tensor.shape[1])
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train loop
epochs = 20
for epoch in range(epochs):
    model.train()
    total_loss = 0.0
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        output = model(batch_X)
        loss = criterion(output, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(train_loader):.4f}")

# Save the model and preprocessor together
torch.save(model.state_dict(), "intrusion_net.pth")
joblib.dump(preprocessor, "dl_preprocessor.pkl")
print("✅ DL model and preprocessor saved.")

Epoch 1/20, Loss: 0.0626
Epoch 2/20, Loss: 0.0282
Epoch 3/20, Loss: 0.0215
Epoch 4/20, Loss: 0.0202
Epoch 5/20, Loss: 0.0180
Epoch 6/20, Loss: 0.0185
Epoch 7/20, Loss: 0.0178
Epoch 8/20, Loss: 0.0156
Epoch 9/20, Loss: 0.0179
Epoch 10/20, Loss: 0.0146
Epoch 11/20, Loss: 0.0152
Epoch 12/20, Loss: 0.0175
Epoch 13/20, Loss: 0.0150
Epoch 14/20, Loss: 0.0150
Epoch 15/20, Loss: 0.0145
Epoch 16/20, Loss: 0.0136
Epoch 17/20, Loss: 0.0143
Epoch 18/20, Loss: 0.0155
Epoch 19/20, Loss: 0.0136
Epoch 20/20, Loss: 0.0128
✅ DL model and preprocessor saved.

In [ ]:
import joblib

log_df = pd.read_csv("logfile11.csv")
X_log = log_df.drop(columns=["level", "binary_attack"], errors="ignore")

# Load preprocessor and transform
preprocessor = joblib.load("dl_preprocessor.pkl")
X_log_processed = preprocessor.transform(X_log)
X_log_tensor = torch.tensor(
    X_log_processed.toarray() if hasattr(X_log_processed, "toarray") else X_log_processed,
    dtype=torch.float32
)

# Load model
model = IntrusionNet(input_dim=X_log_tensor.shape[1])
model.load_state_dict(torch.load("intrusion_net.pth"))
model.eval()

# Predict
with torch.no_grad():
    predictions = model(X_log_tensor).squeeze()
    predicted_labels = (predictions >= 0.5).int().numpy()


mapped_labels = ["abnormal" if p == 1 else "normal" for p in predicted_labels]

output_df = log_df.copy()
output_df["binary_attack"] = mapped_labels
output_df.to_csv("log_with_predictions_dl.csv", index=False)

print("✅ Deep Learning predictions saved to 'log_with_predictions_dl.csv'")
output_df

✅ Deep Learning predictions saved to 'log_with_predictions_dl.csv'

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,Unnamed: 41,binary_attack
0,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1,1,0,0,19,abnormal
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0,0,1,1,21,abnormal
2,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0,0,1,1,21,abnormal
3,0,tcp,http,SF,327,467,0,0,0,0,...,1.00,0.00,0.01,0.03,0,0,0,0,21,normal
4,0,tcp,http,SF,245,351,0,0,0,0,...,1.00,0.00,0.00,0.01,0,0,0,0,21,normal

**Conclusion:** Thus according to the data, Support Vector Machines RBF is the best classifier achieving the highest accuracy, precision, and recall.

<u> **EDA** </u>

**Importing Libraries:**numpy, pandas, matplotlib,pyplot, seaborn, sklearn
(various modules), scipy <br><br>

**Data Preprocessing:**Info of the dataset, checking for null values and converting apt columns to numeric types <br><br>

**Model Training:**Checking for Outliers ,converting 'attack' to binary classification,Label Encoding, Splitting data back into training and testing datasets ,graphs and scaling. <br><br>

**Model Testing:** using Binary Classification Models. Training and evaluating multiple models (Logistic Regression, SVM, Decision Trees, Random Forest, Naive Bayes, K-Nearest Neighbor).<br><br>


**Evaluation based on Compare Metrics:**

Accuracy: Indicates the overall correctness of the model.<br>
Precision: Measures the accuracy of the positive predictions.<br>
Recall: Measures the ability of the model to capture all positive instances.<br>
ROC Curve: Evaluating model performance through ROC curves and calculating the Area Under the Curve (AUC).